"use client";

import { useEffect, useState } from 'react';

export default function ReportsPage() {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const fetchReports = () => {
    fetch('http://localhost:8000/api/reports')
      .then(res => res.json())
      .then(data => {
        setReports(data);
        setLoading(false);
      })
      .catch(err => {
        console.error("Error fetching reports:", err);
        setLoading(false);
      });
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const handleGenerateReport = async () => {
    setGenerating(true);
    try {
      const res = await fetch('http://localhost:8000/api/reports/generate', {
        method: 'POST'
      });
      if (res.ok) {
        fetchReports();
      }
    } catch (err) {
      console.error("Failed to generate report:", err);
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = (report: any) => {
    const content = `
========================================
${report.type.toUpperCase()}
========================================
Date Range: ${report.dateRange}
Health Score: ${report.healthScore}%

Metrics Summary:
- Meetings: ${report.metrics.meetings}
- Decisions: ${report.metrics.decisions}
- Completed Actions: ${report.metrics.completedActions}
- New Risks: ${report.metrics.newRisks}

Governance Breakdown:
----------------------------------------
${report.summary}
----------------------------------------
Generated by Hermes Project Governance Brain
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Governance_Report_${report.dateRange.replace(/ /g, '_')}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const getHealthColor = (score: number) => {
    if (score >= 90) return "text-emerald-600 dark:text-emerald-400";
    if (score >= 80) return "text-blue-600 dark:text-blue-400";
    if (score >= 70) return "text-orange-655 dark:text-orange-400";
    return "text-red-600 dark:text-red-400";
  };

  const getHealthBg = (score: number) => {
    if (score >= 90) return "from-emerald-500/10 to-teal-500/5 dark:from-emerald-500/20 dark:to-teal-500/5 border-emerald-500/30";
    if (score >= 80) return "from-blue-500/10 to-cyan-500/5 dark:from-blue-500/20 dark:to-cyan-500/5 border-blue-500/30";
    if (score >= 70) return "from-orange-500/10 to-amber-500/5 dark:from-orange-500/20 dark:to-amber-500/5 border-orange-500/30";
    return "from-red-500/10 to-rose-500/5 dark:from-red-500/20 dark:to-rose-500/5 border-red-500/30";
  };

  if (loading && reports.length === 0) {
    return <div className="text-zinc-550 dark:text-white text-center py-20 animate-pulse font-medium">Loading reports...</div>;
  }

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-zinc-800 dark:text-white tracking-tight">Reports</h1>
          <p className="text-zinc-550 dark:text-gray-400 mt-1">Review weekly health and process summaries generated by Hermes.</p>
        </div>
        <button 
          onClick={handleGenerateReport}
          disabled={generating}
          className="px-5 py-2 bg-blue-600/85 hover:bg-blue-500/85 text-white rounded-lg transition-all border border-blue-400/30 flex items-center space-x-2 font-medium disabled:opacity-50 cursor-pointer"
        >
          {generating ? (
            <>
              <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
              <span>Generating...</span>
            </>
          ) : (
            <span>Generate New Report</span>
          )}
        </button>
      </div>

      <div className="space-y-6">
        {reports.length === 0 ? (
          <div className="text-center py-16 bg-white/40 dark:bg-white/5 border border-zinc-200 dark:border-white/10 rounded-2xl border-dashed text-zinc-500 dark:text-gray-500 shadow-sm">
            No governance reports generated yet. Click "Generate New Report" to analyze current stats.
          </div>
        ) : (
          reports.map((report) => (
            <div key={report.id} className="rounded-2xl bg-white/40 dark:bg-white/5 border border-zinc-200 dark:border-white/10 p-6 backdrop-blur-sm hover:bg-white/60 dark:hover:bg-white/10 transition-all flex flex-col md:flex-row gap-6 relative overflow-hidden shadow-sm">
              {/* Background Glow */}
              <div className={`absolute top-0 right-0 w-64 h-64 bg-gradient-to-br ${getHealthBg(report.healthScore).split(' ')[0]} opacity-10 dark:opacity-30 blur-3xl rounded-full -mr-20 -mt-20 pointer-events-none`}></div>
              
              <div className="flex-grow space-y-4 z-10">
                <div className="flex justify-between items-start">
                  <div>
                    <div className="flex items-center space-x-3 mb-1">
                      <h2 className="text-xl font-semibold text-zinc-850 dark:text-white">{report.type}</h2>
                      <span className="text-[10px] font-bold text-zinc-500 dark:text-gray-400 uppercase tracking-wider bg-zinc-200/50 dark:bg-black/30 px-2 py-1 rounded-md border border-zinc-300 dark:border-white/5 font-mono">
                        {report.dateRange}
                      </span>
                    </div>
                  </div>
                  <button 
                    onClick={() => handleDownload(report)}
                    className="text-zinc-650 hover:text-zinc-900 dark:text-gray-400 dark:hover:text-white transition-colors p-2 bg-zinc-250/50 dark:bg-black/20 rounded-lg border border-zinc-300 dark:border-white/5 flex items-center space-x-2 group cursor-pointer shadow-sm"
                  >
                    <svg className="w-4 h-4 text-zinc-500 group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path></svg>
                    <span className="text-xs font-semibold">Download Report</span>
                  </button>
                </div>
                
                <p className="text-zinc-700 dark:text-zinc-300 text-sm leading-relaxed max-w-3xl whitespace-pre-wrap">
                  {report.summary}
                </p>

                <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-4 border-t border-zinc-200 dark:border-white/5">
                  <div>
                    <p className="text-2xl font-bold text-zinc-800 dark:text-white">{report.metrics.meetings}</p>
                    <p className="text-[10px] text-zinc-500 dark:text-gray-400 font-bold uppercase tracking-wider">Meetings</p>
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-zinc-800 dark:text-white">{report.metrics.decisions}</p>
                    <p className="text-[10px] text-zinc-500 dark:text-gray-400 font-bold uppercase tracking-wider">Decisions</p>
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-zinc-800 dark:text-white">{report.metrics.completedActions}</p>
                    <p className="text-[10px] text-zinc-500 dark:text-gray-400 font-bold uppercase tracking-wider">Completed Actions</p>
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-zinc-800 dark:text-white">{report.metrics.newRisks}</p>
                    <p className="text-[10px] text-zinc-500 dark:text-gray-400 font-bold uppercase tracking-wider">New Risks</p>
                  </div>
                </div>
              </div>

              <div className="flex-shrink-0 flex items-center justify-center md:w-48 md:border-l border-zinc-200 dark:border-white/10 md:pl-6 z-10">
                <div className={`flex flex-col items-center justify-center w-32 h-32 rounded-full bg-gradient-to-tr ${getHealthBg(report.healthScore)} border shadow-md`}>
                  <p className="text-[10px] text-zinc-600 dark:text-white/70 uppercase tracking-widest font-bold mb-1">Health</p>
                  <p className={`text-4xl font-extrabold ${getHealthColor(report.healthScore)}`}>{report.healthScore}</p>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
